### ISSUE TITLE
stack creation not working for another region

### ISSUE THREAD

**Issue by AnthonyDaSilvaFe** [aws-samples/duomfa-with-amazon-cognito#1]
Hi Mahmoud,

Your project is exactly the information I needed but sadly the S3's bucket s3://duomfa-with-amazon-cognito is not available (due to region maybe) and the stack creation is failing.

Is it possible to provide documentation on how to deploy the Lamdba please?
I tried to do it myself but I'm missing some information and just the js file of the Lambda is not enough it seems.

Regards

**Comment by mmatouk** [comment]
Hi Anthony,

You can download the three lambda packages from the links below. 

https://duomfa-with-amazon-cognito.s3-us-west-2.amazonaws.com/DefineAuthChallenge
https://duomfa-with-amazon-cognito.s3-us-west-2.amazonaws.com/CreateAuthChallenge
https://duomfa-with-amazon-cognito.s3-us-west-2.amazonaws.com/VerifyAuthChallenge

To be able to deploy the stack in another region, you need to create S3 bucket in that region and upload the three files to the new bucket, you then need to make the files public (by selecting the files and going to Actions -> Make Public).

You then need to edit the template UserPoolTemplate.yaml and change each occurrence of CodeUri to point to your newly created bucket.

Let me know if this resolves it.

**Comment by AnthonyDaSilvaFe** [comment]
Hello,

Thanks the deployment worked !
I'll continue to test it.

Regards
